=== amessina71/ame-cards/schema/FIMS-AME.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 sp2 (x64) (http://www.altova.com) by Alberto Messina (RAI - Radiotelevisione Italiana) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="FIMSAMECards">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AMECard" type="AMECardType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="AMECardType">
		<xs:sequence>
			<xs:element name="CardID" type="xs:anyURI"/>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="Type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Audio"/>
						<xs:enumeration value="VIdeo"/>
						<xs:enumeration value="Text"/>
						<xs:enumeration value="Multimodal"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Status">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="draft"/>
						<xs:enumeration value="published"/>
						<xs:enumeration value="publisheable"/>
						<xs:enumeration value="finalreview"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Editor" type="xs:string"/>
			<xs:element name="Alias" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Tag" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Definition" type="xs:string"/>
			<xs:element name="Reference" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Example" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Remarks" minOccurs="0"/>
			<xs:element name="Parameters">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Inputs">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Input" type="inputParameterType" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="Outputs">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Output" type="outputParameterType" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="CapabilityGroup" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Capability" type="capabilityType" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="name" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="parameterType" abstract="true">
		<xs:sequence>
			<xs:element name="Name" type="xs:NMTOKEN"/>
			<xs:element name="Type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="controlled vocabulary"/>
						<xs:enumeration value="xml"/>
						<xs:enumeration value="text"/>
						<xs:enumeration value="URL"/>
						<xs:enumeration value="float"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Representation" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Unit" minOccurs="0"/>
			<xs:element name="Comment" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="inputParameterType">
		<xs:complexContent>
			<xs:extension base="parameterType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="outputParameterType">
		<xs:complexContent>
			<xs:extension base="parameterType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="capabilityType">
		<xs:sequence>
			<xs:element name="Values">
				<xs:simpleType>
					<xs:union memberTypes="xs:anyURI xs:string"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Type">
				<xs:simpleType>
					<xs:restriction base="capabilityElement"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Unit" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="capabilityElement">
		<xs:restriction base="xs:string">
			<xs:enumeration value="supported audio formats"/>
			<xs:enumeration value="supported audio codec"/>
			<xs:enumeration value="result type"/>
			<xs:enumeration value="supported languages"/>
			<xs:enumeration value="supported recording conditions"/>
			<xs:enumeration value="supported speech types"/>
			<xs:enumeration value="supported video formats"/>
			<xs:enumeration value="supported image formats"/>
			<xs:enumeration value="supported scripts"/>
			<xs:enumeration value="recognisable text types"/>
			<xs:enumeration value="minimum text size"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== amessina71/ame-cards/cards/SceneStorySegmentation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Werner Bailer (JOANNEUM RESEARCH) -->
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>M001</CardID>
		<Name>Scene/story segmentation</Name>
		<Type>Multimodal</Type>
		<Status>draft</Status>
		<Editor>Werner</Editor>
		<Definition>Segment an audiovisual segment into semantic temporal units, such as news stories, scenes, etc.</Definition>
		<Parameters>
			<Inputs>
				<Input>
					<Name>MinDuration</Name>
					<Type>float</Type>
					<Unit>seconds</Unit>
					<Comment>Minimum duration of a segment to be reported (optional, default: 0).</Comment>
				</Input>
				<Input>
					<Name>MaxDuration</Name>
					<Type>float</Type>
					<Unit>seconds</Unit>
					<Comment>Maximium duration of a segment to be reported (optional, default: inf).</Comment>
				</Input>				
			</Inputs>
			<Outputs>
				<Output>
					<Name>Segmentation</Name>
					<Type>xml</Type>
					<Representation>urn:mpeg:mpeg7:schema:2004:TemporalDecompositionType</Representation>
					<Comment>The timeline of segments with their start and end times.</Comment>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup name="modalities">
			<Capability>
				<Values>urn:ebu:metadata-cs:ContentGenreCS</Values>
				<Type>supported genres</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup name="genres">
			<Capability>
				<Values>urn:modalities</Values>
				<Type>supported modalities</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup name="input formats">
			<Capability>
				<Values>urn:cvds</Values>
				<Type>supported video formats</Type>
			</Capability>
			<Capability>
				<Values>urn:sdhfsdjkfh</Values>
				<Type>supported image formats</Type>
			</Capability>
			<Capability>
				<Values>urn:sdhfsdjkfh</Values>
				<Type>supported audio formats</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== amessina71/ame-cards/cards/CopyDetectionIndexing.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 sp2 (x64) (http://www.altova.com) by Alberto Messina (RAI - Radiotelevisione Italiana) -->
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>V002</CardID>
		<Name>Copy Detection (Indexing)</Name>
		<Type>Video</Type>
		<Status>draft</Status>
		<Editor>Werner</Editor>
	
		<!-- Copy detection (indexing)	Extract features from a video and index them in a database for later matching.	
			
    Target size of the descriptor (average bytes/sec)
    Identifier of the database
    
	 	
	 	
    Supported video codecs
    Minimum length of match
    Supported descriptor sizes
    
	 -->
		
		
		<Definition>Extract descriptors/fingerprints from a video and index them in a database for later matching.</Definition>
		<Parameters>
			<Inputs>
				<Input>
					<Name>TargetDescriptorSize</Name>
					<Type>integer</Type>
					<Unit>bytes/second</Unit>
				</Input>
				<Input>
					<Name>DBIdentifier</Name>
					<Type>URL</Type>
					<Comment>The identifier of the database in which the descriptors/fingerprints shall be indexed.</Comment>
				</Input>
			</Inputs>
			<Outputs>
				<Output>
					<Name>dummy</Name>
					<Type>text</Type>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup name="Descriptor sizes">
			<Capability>
				<Values>urn:oiweuowieru</Values>
				<Type>supported descriptor sizes</Type>
				<Unit>bytes/second</Unit>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup name="input formats">
			<Capability>
				<Values>urn:cvds</Values>
				<Type>supported video formats</Type>
			</Capability>
			<Capability>
				<Values>urn:sdhfsdjkfh</Values>
				<Type>supported image formats</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== amessina71/ame-cards/cards/SpeakerRecognitionTraining.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 rel. 3 (x64) (http://www.altova.com) by Lauri Saarikoski (Yle - The Finnish Broadcasting Company) -->
<!-- Output type for actual speaker model? -->
<!-- Language dependant? -->
<!-- Input audio fragment not needed as input? -->
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>A004</CardID>
		<Name>Speaker recognition training</Name>
		<Type>Audio</Type>
		<Status>draft</Status>
		<Editor>Lauri</Editor>
		<Definition>Train models for a speaker recognition system</Definition>
		<Parameters>
			<Inputs>
				<Input>
					<Name>InputAudioFragment</Name>
					<Type>URL</Type>
				</Input>
				<Input>
					<Name>SpeakerModelReference</Name>
					<Type>URL</Type>
				</Input>
			</Inputs>
			<Outputs>
				<Output>
					<Name>TrainedSpeakerModelReference</Name>
					<Type>URL</Type>
				</Output>
				<Output>
					<Name>WasTrainingSuccess</Name>
					<Type>text</Type>
					<Representation/>
				</Output>
				<Output>
					<Name>TrainedSpeakerModel</Name>
					<Type>URL</Type>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup name="input formats">
			<Capability>
				<Values>urn:cvds</Values>
				<Type>supported audio codec</Type>
			</Capability>
			<Capability>
				<Values>urn:sdhfsdjkfh</Values>
				<Type>supported audio formats</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== amessina71/ame-cards/cards/POSTagging.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Werner Bailer (JOANNEUM RESEARCH) -->
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>T001</CardID>
		<Name>Part of speech tagging</Name>
		<Type>Text</Type>
		<Status>draft</Status>
		<Editor>Werner</Editor>
		<Definition>The allocation of categories and relationships of words in a sentence. F.e. verbs or nouns (plural/...).</Definition>
		<Parameters>
			<Inputs>
				<Input>
					<Name>InputText</Name>
					<Type>text</Type>
					<Representation>TBD, could also be XML</Representation>
					<Comment>The input text to be processed (required)</Comment>
				</Input>			
			</Inputs>
			<Outputs>
				<Output>
					<Name>TaggedWords</Name>
					<Type>xml</Type>
					<Representation>urn:tbd</Representation>
					<Comment>A list of tagged words, for each the disambiguated category, relationship with other words, confidence score</Comment>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup name="Text Types">
			<Capability>
				<Values>urn:oiweuowieru</Values>
				<Type>supported languages</Type>
			</Capability>
			<Capability>
				<Values>urn:sfsdjkh</Values>
				<Type>supported scripts</Type>
			</Capability>
		</CapabilityGroup>
		
		<CapabilityGroup name="input formats">
			<Capability>
				<Values>urn:cvds</Values>
				<Type>supported text formats</Type>
			</Capability>
		</CapabilityGroup>
		
	</AMECard>
</FIMSAMECards>
